services:
  # Use in production.
  # Add your email in command below, uncomment labels in other services (and add your domains there)
  # to issue ssl certificates
  # traefik:
  #   image: traefik:v3
  #   command:
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"
  #     - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
  #     - "--certificatesresolvers.letsencrypt.acme.email=youremail@domain.com"
  #     - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
  #     - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  #     - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "./letsencrypt:/letsencrypt"
  #   restart: unless-stopped
  #   networks:
  #     - saleor-backend-tier

  api:
    image: ghcr.io/saleor/saleor:3.23
    # user: "1000:1000" # production only
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - db
      - cache
      - jaeger
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    # Production only - Uncomment and change domain below.
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.api.rule=Host(`api.domain.com`)"
    #   - "traefik.http.routers.api.entrypoints=websecure"
    #   - "traefik.http.routers.api.tls.certresolver=letsencrypt"
    #   - "traefik.http.services.api.loadbalancer.server.port=8000"

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.23
    ports:
      - 9000:80
    restart: unless-stopped
    environment:
      - API_URI=http://localhost:8000/graphql/ # replace API_URI with API_URL in production
    # Production only - Uncomment and change domain below.
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.dashboard.rule=Host(`admin.domain.com`)"
    #   - "traefik.http.routers.dashboard.entrypoints=websecure"
    #   - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
    #   - "traefik.http.services.dashboard.loadbalancer.server.port=80"

  # Remove db block entirely in production
  db:
    image: library/postgres:15-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql:ro,z
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  cache:
    image: valkey/valkey:8.1-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-cache:/data

  worker:
    image: ghcr.io/saleor/saleor:3.23
    # user: "1000:1000" # production only
    # In production remove '-B' from the below command and add celery-beat (see below)
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file:
      - common.env
      - backend.env
    depends_on:
      - cache
      - mailpit # remove in prod
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media

  # In production use below celery-beat service separating it out from worker to avoid errors
  # celery-beat:
  #   image: ghcr.io/saleor/saleor:3.23
  #   user: "1000:1000"
  #   command: celery -A saleor --app=saleor.celeryconf:app beat --loglevel=info -s /tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid
  #   restart: unless-stopped
  #   networks:
  #     - saleor-backend-tier
  #   env_file:
  #     - common.env
  #     - backend.env
  #   depends_on:
  #     - cache
  #   volumes:
  #     - saleor-media:/app/media

  # Keep or remove in production based on your requirements
  jaeger:
    image: jaegertracing/jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - type: tmpfs
        target: /tmp

  # Remove in production
  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  # Remove saleor-db in production
  saleor-db:
    driver: local
  saleor-cache:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
